### ISSUE TITLE
What does the -CurrentShort-actually means?

### ISSUE THREAD

**Issue by tydaytygx** [Cruze03/CSGO-PugSetup-RoundRestore#1]
@Cruze03 I noticed this great plugin just now. Now I want to translate it to my local language for usage.
```
"CurrentShort"
	{
		"en"			" [Curr]"
	}
```
Could you tell me what is the meaning of this variable?
Is that a snapshot of roud or something else?
Thanks a lot!

**Comment by tydaytygx** [comment]
Is [Curr] just a tag showing the current roud when the menu shows?

**Comment by Cruze03** [comment]
Yes!

**Comment by lugaamn** [comment]
every player using .rest .restore commands. need admin flag

**Comment by tydaytygx** [comment]
> 
> 
> every player using .rest .restore commands. need admin flag

Thanks for your reply.
